export const mockMeals = [
  {
    id: '001',
    name: 'Mediterranean Power Bowl',
    description: 'Grilled chicken, quinoa, roasted vegetables, hummus, and tahini dressing',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1572319216151-4fb52730dc68?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwbWVhbCUyMGJvd2x8ZW58MXx8fHwxNzYxMDU3MjY2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    type: ['High Protein', 'Gluten-Free'],
    calories: 520,
    protein: 38,
    carbs: 45,
    fat: 18,
    status: 'available',
    stock: 45,
    rating: 4.8,
    reviews: 127,
  },
  {
    id: '002',
    name: 'Vegan Rainbow Salad',
    description: 'Fresh greens, chickpeas, avocado, beets, and lemon-herb vinaigrette',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1585138548795-fa869d44af7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2ZWdhbiUyMHNhbGFkJTIwZnJlc2h8ZW58MXx8fHwxNzYxMDk4ODc3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    type: ['Vegan', 'Low Calorie'],
    calories: 380,
    protein: 12,
    carbs: 32,
    fat: 22,
    status: 'available',
    stock: 32,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: '003',
    name: 'Keto Steak Bowl',
    description: 'Grass-fed beef, cauliflower rice, broccoli, and garlic butter',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1620041630998-e147e143468c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxrZXRvJTIwbWVhbCUyMHByb3RlaW58ZW58MXx8fHwxNzYxMTU4MzU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    type: ['Keto', 'High Protein'],
    calories: 480,
    protein: 42,
    carbs: 8,
    fat: 32,
    status: 'available',
    stock: 28,
    rating: 4.9,
    reviews: 203,
  },
  {
    id: '004',
    name: 'Asian Fusion Box',
    description: 'Teriyaki salmon, jasmine rice, edamame, and sesame vegetables',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1722614170069-cd28c9558a10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcmVwYXJlZCUyMG1lYWxzJTIwZGVsaXZlcnl8ZW58MXx8fHwxNzYxMTU4MzU2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    type: ['High Protein', 'Omega-3'],
    calories: 560,
    protein: 36,
    carbs: 52,
    fat: 20,
    status: 'available',
    stock: 18,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: '005',
    name: 'Italian Pasta Primavera',
    description: 'Whole wheat pasta, seasonal vegetables, marinara, and fresh basil',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1662993924949-2b2d68c08cee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwZm9vZCUyMGJveHxlbnwxfHx8fDE3NjExNTgzNTZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    type: ['Vegetarian', 'Comfort Food'],
    calories: 450,
    protein: 14,
    carbs: 68,
    fat: 12,
    status: 'available',
    stock: 5,
    rating: 4.5,
    reviews: 98,
  },
  {
    id: '006',
    name: 'Southwest Chicken Bowl',
    description: 'Grilled chicken, black beans, corn, peppers, and chipotle sauce',
    price: 12.49,
    image: 'https://images.unsplash.com/photo-1585730315658-faf260d0d335?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnb3VybWV0JTIwbWVhbCUyMHByZXB8ZW58MXx8fHwxNzYxMTU4MzU2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    type: ['High Protein', 'Spicy'],
    calories: 510,
    protein: 40,
    carbs: 48,
    fat: 16,
    status: 'available',
    stock: 38,
    rating: 4.8,
    reviews: 174,
  },
];

export const mockUsers = [
  {
    id: '1',
    username: 'customer1',
    email: 'john.doe@email.com',
    firstName: 'John',
    lastName: 'Doe',
    phone: '(555) 123-4567',
    role: 'customer',
    loyaltyPoints: 1250,
    totalSpent: 2345.67,
    address: '123 Main St, Anytown, ST 12345',
    status: 'active',
  },
  {
    id: '2',
    username: 'admin',
    email: 'admin@bento.com',
    firstName: 'Admin',
    lastName: 'User',
    phone: '(555) 999-0000',
    role: 'admin',
    status: 'active',
  },
  {
    id: '3',
    username: 'staff1',
    email: 'staff@bento.com',
    firstName: 'John',
    lastName: 'Smith',
    phone: '(555) 987-6543',
    role: 'staff',
    status: 'active',
  },
];

export const mockPaymentMethods = [
  {
    id: '1',
    type: 'credit',
    last4: '1234',
    name: 'John Doe',
    expiry: '12/25',
  },
  {
    id: '2',
    type: 'applepay',
    last4: '5678',
    name: 'John Doe',
  },
];

export const mockOrders = [
  {
    id: '1234',
    customerId: '1',
    items: [
      { meal: mockMeals[0], quantity: 2 },
      { meal: mockMeals[1], quantity: 1 },
    ],
    total: 36.97,
    status: 'delivered',
    date: '2025-10-15',
    deliveryDate: '2025-10-17',
    trackingNumber: 'UPS123456789',
    paymentMethod: 'Visa ****1234',
    address: '123 Main St, Anytown, ST 12345',
  },
  {
    id: '1233',
    customerId: '1',
    items: [{ meal: mockMeals[2], quantity: 3 }],
    total: 44.97,
    status: 'refunded',
    date: '2025-10-14',
    paymentMethod: 'Visa ****1234',
    address: '123 Main St, Anytown, ST 12345',
  },
  {
    id: '1235',
    customerId: '1',
    items: [
      { meal: mockMeals[3], quantity: 1 },
      { meal: mockMeals[4], quantity: 2 },
    ],
    total: 37.97,
    status: 'processing',
    date: '2025-10-20',
    paymentMethod: 'Apple Pay',
    address: '123 Main St, Anytown, ST 12345',
  },
];

export const mockPromotions = [
  {
    id: '1',
    code: 'SPRING20',
    name: 'Spring Special',
    description: 'Get 20% off your entire order this spring season',
    type: '20% Off',
    discount: 20,
    expiryDate: '2026-03-31',
    status: 'active',
    usageCount: 234,
  },
  {
    id: '2',
    code: 'BOGO50',
    name: 'Buy One Get One 50% Off',
    description: 'Purchase any meal and get your second meal at half price',
    type: 'BOGO 50% Off',
    discount: 50,
    expiryDate: '2026-03-31',
    status: 'active',
    usageCount: 156,
  },
  {
    id: '3',
    code: 'WELCOME10',
    name: 'Welcome Offer',
    description: 'New customers get 10% off their first order',
    type: '10% Off First Order',
    discount: 10,
    expiryDate: '2026-12-31',
    status: 'active',
    usageCount: 89,
  },
];